### ISSUE TITLE
TypeError: train() takes 3 positional arguments but 252 were given

### ISSUE THREAD

**Issue by briacwg** [dinever/antispam#7]
Is there a possibility to add more than 3 arguments?

**Comment by Gupta-Aryaman** [comment]
could you please elaborate? train's definition consists of only 2 parameters

**Comment by briacwg** [comment]
How do I just load my own model? I have a list of 200k or so words I would like to use for training.

**Comment by Gupta-Aryaman** [comment]
Please share some part of the dataset so that I can take a look

**Comment by briacwg** [comment]
import antispam

d = antispam.Detector("model1.json")

d.train('considera', 'cerberus', 'peritricha', 'padfolios', 'lindas', 'vswkw', 'antiguas', 'unpunishing', 'conscript', 'ofaj', 'mihrozsbi', 'cyfe', 'gdghlieegq', 'zitda', 'yqzfkibx', 'suceeded', 'jxgixkpnx', 'charlottplanet', 'realistically', 'podmiotu', 'distanc', 'feok', 'perils', True)
d.train("Hi John, could you please come to my office by 3pm? Ding", False) 
# This line would have 700+ considered "Unspam" emails 

msg1 = "Cheap shoes for sale at DSW shoe store!"
print(d.score(msg1))


print(d.is_spam(msg1))


msg2 = "Hi mark could you please send me a copy of your machine learning homework? thanks"
print(d.score(msg2))


print(d.is_spam(msg2))


d.save()

# I am looking to build something which would be able to print all emails from a special email. Using this antispam detector we use the words that qualify the email as SPAM. But before we use a percentage. This percentage would determine the probability of the email to be spam or not. I don't really know if this is the right thing to use.

I appreciate your help.

**Comment by Gupta-Aryaman** [comment]
understood, i am trying to understand your model, and how you are making it learn...as I am not much into Machine Learning
it may take me longer than usual (a week?). If you can wait for that long, then please assign me the issue

**Comment by briacwg** [comment]
I can wait as long as you need. How do I assign the issue?

**Comment by Gupta-Aryaman** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users

**Comment by briacwg** [comment]
I don't think I am able to do this. @dinever might have to do it since I dont have the perms to do so.

**Comment by Gupta-Aryaman** [comment]
OK i will work on it anyways, but not sure if it would get merged as owner doesn't seem to be active

**Comment by briacwg** [comment]
Yes that's not a problem. Thank you for your help

**Comment by briacwg** [comment]
Any news @Gupta-Aryaman ?

**Comment by Gupta-Aryaman** [comment]
Working on your issue only

**Comment by Gupta-Aryaman** [comment]
and also please share the json file you are using to train the model

**Comment by Gupta-Aryaman** [comment]
please share all the data you are using to train the model

**Comment by Gupta-Aryaman** [comment]
see i found the issue
![image](https://user-images.githubusercontent.com/34962578/197239807-10752f5a-14c4-4e02-80ea-57ab7cc3b086.png)
this is how we are training the model.
what you did was to insert all the true values in a single time.
I think the resolution is that lets create a csv file where each row would be like - 
[data, bool]
example - ["Hi John, could you please come to my office by 3pm? Ding", False]
we can iterate through each row in the csv file to train the model
and Voila! your problem is solved

**Comment by Gupta-Aryaman** [comment]
you could create the csv file yourself, or send me the data i will do that for you and do the iteration as well

**Comment by Gupta-Aryaman** [comment]
@HocariFounder

**Comment by Gupta-Aryaman** [comment]
@HocariFounder

**Comment by briacwg** [comment]
Thanks
